; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0-beta2"

projects[community_tags][subdir] = "contrib"
projects[community_tags][version] = "1.0"

projects[contact_permissions][subdir] = "contrib"
projects[contact_permissions][version] = "1.x-dev"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[content_lock][subdir] = "contrib"
projects[content_lock][version] = "1.4"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.2"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[fancy_login][subdir] = "contrib"
projects[fancy_login][version] = "1.0-beta2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-beta2"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[feeds_jsonpath_parser][subdir] = "contrib"
projects[feeds_jsonpath_parser][version] = "1.0-beta2+10-dev"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[fivestar][subdir] = "contrib"
projects[fivestar][version] = "2.0-alpha2"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "1.1"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.7"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[markup][subdir] = "contrib"
projects[markup][version] = "1.1-beta1"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc5"

projects[mass_contact][subdir] = "contrib"
projects[mass_contact][version] = "1.0-beta2"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc2"

projects[multiselect][subdir] = "contrib"
projects[multiselect][version] = "1.9+10-dev"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[nodeaccess_userreference][subdir] = "contrib"
projects[nodeaccess_userreference][version] = "3.10"

projects[nodereference_url][subdir] = "contrib"
projects[nodereference_url][version] = "1.12"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.2"

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[plus1][subdir] = "contrib"
projects[plus1][version] = "1.0-alpha1+11-dev"

projects[quickbar][subdir] = "patched"
projects[quickbar][version] = "2.0-beta1+28-dev"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.3"

projects[select_or_other][subdir] = "contrib"
projects[select_or_other][version] = "2.20"

projects[sharethis][subdir] = "contrib"
projects[sharethis][version] = "2.5"

projects[simplify][subdir] = "contrib"
projects[simplify][version] = "3.1"

projects[stringoverrides][subdir] = "contrib"
projects[stringoverrides][version] = "1.8"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[superfish][subdir] = "contrib"
projects[superfish][version] = "1.8"

projects[title_field_ui][subdir] = "contrib"
projects[title_field_ui][version] = "1.0-alpha1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[tweet_feed][subdir] = "contrib"
projects[tweet_feed][version] = "1.7"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta5+11-dev"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta7"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.11"

projects[vscc][subdir] = "contrib"
projects[vscc][version] = "1.x-dev"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][version] = "3.1"

projects[nucleus][subdir] = "nucleus/nucleus"
projects[nucleus][version] = "1.3"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cwcon_custom][download][type] = ""
projects[cwcon_custom][download][url] = ""
projects[cwcon_custom][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[cwcon_2015][download][type] = ""
projects[cwcon_2015][download][url] = ""
projects[cwcon_2015][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[dompdf][download][type] = ""
libraries[dompdf][download][url] = ""
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tcpdf][download][type] = ""
libraries[tcpdf][download][url] = ""
libraries[tcpdf][directory_name] = "tcpdf"
libraries[tcpdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery_ui_multiselect][download][type] = ""
libraries[jquery_ui_multiselect][download][url] = ""
libraries[jquery_ui_multiselect][directory_name] = "jquery_ui_multiselect"
libraries[jquery_ui_multiselect][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

